version: 2.1
orbs:
  node: circleci/node@4.2.1
workflows:
  node-tests:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: node:15.14.0
      - image: mongo:4.2.0
        environment:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test
    working_directory: ~/perfil_do_ciclista
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Seed database
          command: 'npm run seed:test'
      - run:
          name: Run tests
          command: 'npm test'