version: 2.1
orbs:
  node: circleci/node@4.2.1
workflows:
  build_and_test:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout
            - lint
            - test
          filters:
            branches:
              only: master

jobs:
  checkout:
    working_directory: ~/perfil_do_ciclista
    docker:
      - image: node:15.14.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  lint:
    working_directory: ~/perfil_do_ciclista
    docker:
      - image: node:15.14.0
    steps:
      - run:
          name: Run linter
          command: 'npm run lint'

  test:
    working_directory: ~/perfil_do_ciclista
    docker:
      - image: node:15.14.0
        environment:
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 27017
          TEST_DB_USERNAME: test
          TEST_DB_PASSWORD: test
          TEST_DB_NAME: test
          NODE_ENV: test
      - image: mongo:4.2.0
        environment:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test
    steps:
      - run:
          name: Run tests
          command: 'npm run test:ci'
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

  build:
    working_directory: ~/perfil_do_ciclista
    docker:
      - image: node:15.14.0
    steps:
      - run:
          name: Run build
          command: 'npm run build'