version: 2.1
orbs:
  node: circleci/node@4.2.1
workflows:
  node-tests:
    jobs:
      - node/test

jobs:
  node/test:
    docker:
      - image: node:15.14.0
      - image: mongo:4.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Seed database
          command: npm run db:seed:profile
      - run:
          name: Run tests
          command: npm test